/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package passwordstorage;

import java.io.*;
import java.net.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import static passwordstorage.Actions.SymbolEx;

/**
 *
 * @author Marcius
 */
public class PasswordStorageUI extends javax.swing.JFrame {

    /**
     * Creates new form PasswordStorageUI
     */
    public PasswordStorageUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Login_window = new javax.swing.JPanel();
        Login_username = new javax.swing.JTextField();
        Login_password = new javax.swing.JTextField();
        Login_Button = new javax.swing.JButton();
        Login_reg = new javax.swing.JButton();
        Login_dialog = new javax.swing.JLabel();
        Menu_window = new javax.swing.JPanel();
        Menu_add = new javax.swing.JButton();
        Menu_show = new javax.swing.JButton();
        Menu_logout = new javax.swing.JButton();
        Menu_username = new javax.swing.JLabel();
        Show_window = new javax.swing.JPanel();
        Show_back = new javax.swing.JButton();
        Add_window = new javax.swing.JPanel();
        Add_back = new javax.swing.JButton();
        Add_add = new javax.swing.JButton();
        Add_url = new javax.swing.JTextField();
        Add_pass = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        Login_window.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Login_windowMouseEntered(evt);
            }
        });

        Login_username.setText("Username");
        Login_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_usernameActionPerformed(evt);
            }
        });

        Login_password.setText("Password");

        Login_Button.setText("Enter");
        Login_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_ButtonActionPerformed(evt);
            }
        });

        Login_reg.setText("Register");
        Login_reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_regActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Login_windowLayout = new javax.swing.GroupLayout(Login_window);
        Login_window.setLayout(Login_windowLayout);
        Login_windowLayout.setHorizontalGroup(
            Login_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Login_windowLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(Login_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Login_windowLayout.createSequentialGroup()
                        .addGroup(Login_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Login_username)
                            .addComponent(Login_password)
                            .addComponent(Login_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Login_reg, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addGap(0, 125, Short.MAX_VALUE))
                    .addComponent(Login_dialog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        Login_windowLayout.setVerticalGroup(
            Login_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Login_windowLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(Login_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Login_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Login_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Login_reg)
                .addGap(18, 18, 18)
                .addComponent(Login_dialog, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        Menu_add.setText("Add");
        Menu_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_addActionPerformed(evt);
            }
        });

        Menu_show.setText("Show");
        Menu_show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_showActionPerformed(evt);
            }
        });

        Menu_logout.setText("Log out");
        Menu_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_logoutActionPerformed(evt);
            }
        });

        Menu_username.setText("jLabel1");

        javax.swing.GroupLayout Menu_windowLayout = new javax.swing.GroupLayout(Menu_window);
        Menu_window.setLayout(Menu_windowLayout);
        Menu_windowLayout.setHorizontalGroup(
            Menu_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Menu_windowLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(Menu_show)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Menu_add)
                .addContainerGap(87, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Menu_windowLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Menu_logout)
                .addGap(109, 109, 109))
            .addGroup(Menu_windowLayout.createSequentialGroup()
                .addComponent(Menu_username)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Menu_windowLayout.setVerticalGroup(
            Menu_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Menu_windowLayout.createSequentialGroup()
                .addComponent(Menu_username)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(Menu_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Menu_add)
                    .addComponent(Menu_show))
                .addGap(45, 45, 45)
                .addComponent(Menu_logout)
                .addGap(26, 26, 26))
        );

        Show_back.setText("Back");
        Show_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Show_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Show_windowLayout = new javax.swing.GroupLayout(Show_window);
        Show_window.setLayout(Show_windowLayout);
        Show_windowLayout.setHorizontalGroup(
            Show_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Show_windowLayout.createSequentialGroup()
                .addComponent(Show_back, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 269, Short.MAX_VALUE))
        );
        Show_windowLayout.setVerticalGroup(
            Show_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Show_windowLayout.createSequentialGroup()
                .addGap(0, 261, Short.MAX_VALUE)
                .addComponent(Show_back))
        );

        Add_back.setText("Back");
        Add_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_backActionPerformed(evt);
            }
        });

        Add_add.setText("Add");
        Add_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_addActionPerformed(evt);
            }
        });

        Add_url.setText("URL");

        Add_pass.setText("Password");

        javax.swing.GroupLayout Add_windowLayout = new javax.swing.GroupLayout(Add_window);
        Add_window.setLayout(Add_windowLayout);
        Add_windowLayout.setHorizontalGroup(
            Add_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Add_windowLayout.createSequentialGroup()
                .addComponent(Add_back, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(Add_windowLayout.createSequentialGroup()
                .addGroup(Add_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Add_windowLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(Add_add, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Add_windowLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(Add_url, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(Add_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        Add_windowLayout.setVerticalGroup(
            Add_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Add_windowLayout.createSequentialGroup()
                .addGap(0, 142, Short.MAX_VALUE)
                .addGroup(Add_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Add_url, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Add_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Add_add)
                .addGap(87, 87, 87)
                .addComponent(Add_back))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 361, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Login_window, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Menu_window, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Show_window, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Add_window, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 306, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Login_window, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Menu_window, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Show_window, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Add_window, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Login_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_ButtonActionPerformed
        // TODO add your handling code here:
        String username = Login_username.getText();
        String password = Login_password.getText();
        try {
            //Actions.login(username, password);
            if (Actions.login(username, password)) {
                Menu_username.setText(username);
                Login_window.setVisible(false);
                Menu_window.setVisible(true);
            } else {
                Login_dialog.setText("Invalid information!");
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(PasswordStorageUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Login_ButtonActionPerformed

    private void Login_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Login_usernameActionPerformed

    private void Menu_showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_showActionPerformed
        // TODO add your handling code here:
        Menu_window.setVisible(false);
        Add_window.setVisible(true);
    }//GEN-LAST:event_Menu_showActionPerformed

    private void Menu_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_addActionPerformed
        // TODO add your handling code here:
        Menu_window.setVisible(false);
        Show_window.setVisible(true);
    }//GEN-LAST:event_Menu_addActionPerformed

    private void Menu_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_logoutActionPerformed
        // TODO add your handling code here:
        Menu_window.setVisible(false);
        Login_window.setVisible(true);
    }//GEN-LAST:event_Menu_logoutActionPerformed

    private void Add_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_backActionPerformed
        // TODO add your handling code here:
        Add_window.setVisible(false);
        Menu_window.setVisible(true);
    }//GEN-LAST:event_Add_backActionPerformed

    private void Show_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Show_backActionPerformed
        // TODO add your handling code here:
        Show_window.setVisible(false);
        Menu_window.setVisible(true);
    }//GEN-LAST:event_Show_backActionPerformed

    private void Login_windowMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Login_windowMouseEntered
        // TODO add your handling code here:
        Show_window.setVisible(false);
        Add_window.setVisible(false);
        Menu_window.setVisible(false);
    }//GEN-LAST:event_Login_windowMouseEntered

    private void Login_regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_regActionPerformed
        // TODO add your handling code here:
        String username = Login_username.getText();
        String password = Login_password.getText();
        try {
            if (Actions.exists(username)) {
                //error msg exists
                Login_dialog.setText("User already registered!");
            } else if (!(SymbolEx(username, password))) {
                Login_dialog.setText("Invalid symbols! Or credentials too short!");
            } else {
                Actions.register(username, password);
                Login_dialog.setText("User succesfully registered!");
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(PasswordStorageUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(PasswordStorageUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Login_regActionPerformed

    private void Add_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_addActionPerformed
        // TODO add your handling code here:
       String URL = Add_url.getText();
       String password = Add_pass.getText();
        try {
            Actions.Add(URL, password, Menu_username.getText());
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(PasswordStorageUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(PasswordStorageUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Add_addActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html    
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PasswordStorageUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PasswordStorageUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PasswordStorageUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PasswordStorageUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PasswordStorageUI().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_add;
    private javax.swing.JButton Add_back;
    private javax.swing.JTextField Add_pass;
    private javax.swing.JTextField Add_url;
    private javax.swing.JPanel Add_window;
    private javax.swing.JButton Login_Button;
    private javax.swing.JLabel Login_dialog;
    private javax.swing.JTextField Login_password;
    private javax.swing.JButton Login_reg;
    private javax.swing.JTextField Login_username;
    private javax.swing.JPanel Login_window;
    private javax.swing.JButton Menu_add;
    private javax.swing.JButton Menu_logout;
    private javax.swing.JButton Menu_show;
    private javax.swing.JLabel Menu_username;
    private javax.swing.JPanel Menu_window;
    private javax.swing.JButton Show_back;
    private javax.swing.JPanel Show_window;
    // End of variables declaration//GEN-END:variables
}
